### ISSUE TITLE
feat: Backend>Create a Error Handler async fo handling async Errors

### ISSUE THREAD

**Issue by moizextra** [abdulmoizsheraz/Mern-Stack-Learning#3]
feat: Backend>Create a Error Handler async fo handling async Errors

**Comment by RaturiAR7** [comment]
I would like to work on this.

**Comment by Nis7538** [comment]
Hey, I would like to work on this issue. Can you assign me the same under hacktoberfest?

**Comment by moizextra** [comment]
Ok 
This Project is under Hacktoberfest

**Comment by Nis7538** [comment]
You need an asyncWrapper to replace the try catch block in each controller right?

**Comment by moizextra** [comment]
> You need an asyncWrapper to replace the try catch block in each controller right?

Right

**Comment by Nis7538** [comment]
Created a PR regarding the issue, please review and merge it

**Comment by Nis7538** [comment]
Can you add the hacktoberfest-accepted label to the pr?

**Comment by moizextra** [comment]
> Can you add the hacktoberfest-accepted label to the pr?

ok
